### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by carolsinc** [carolsinc/web-design-2-independent-project#10]
I believe this website deserves an A. I worked very hard to achieve many elements of the site. With nearly all the html done I scrapped it all and started again to ensure the best and most accessible site I was capable of making. I learned javascript so I could include a functioning apple map. The grid layout for a responsive menu was very challenging. The favicon was also very difficult, as I had to try several different generators to have all the necessary sizes.  

@hellachella

**Comment by hellachella** [comment]
You did such a good job
